:sparkles: Wait to start playing or rendering until movie is ready
etro-js/etro pull request #160
Opened 2022-10-12 20:45 UTC by yvz5

I cant seem to fix the tests. Linter complains that I cant have an async Promise resolver. If I dont use a Promise inside the play promise, the tests are green. I wanted to use the `_waitForReady` as a Promise because it makes the code readable and it would wait 100 ms for the next retry. Without a Promise the only option I can think of is a while loop. Let me know what you think about the issue. 
Fixes  #149

2022-10-13 14:45 UTC, clabe45 requested changes
Thanks for contributing again 🔥 🔥 

This PR looks great, but a few things can be changed:
- `setTimeout()` should be replaced with `window.requestAnimationFrame()`
- I didn't realize that `_waitForReady()` should be available to users and tests. Can you make it public and rename it to something easier for users to remember like `load()`?
- Fix the failing tests by making them async and adding `await movie.load()` or `await movie.play()` where necessary. (Some tests check the state when the movie is playing, while others wait for it to end before the assertions.)

2022-10-13 18:16 UTC, yvz5 commented
@clabe45  thanks for your reply. `_waitForReady` is actually a helper method. I was planning to make `_render` method also wait until move is ready. So `_waitForReady` is private and should not be used by api users I though. Should I still rename it to `load` ? I think it might be misleading because all it does is to wait for movie to turn `ready = true`. I am not so sure about the change here.

2022-10-14 12:04 UTC, clabe45 commented
Good point, users don't really need this method.

In the test that checks if movie.paused is false while it's playing, force it to load beforehand. This can be done by patching its layer's ready getter (or something along those lines, I'm on mobile right now so I can't check). 

_render() already repeats and waits for the movie to load before rendering anything, so no changes should be required there.

2022-10-14 12:12 UTC, clabe45 commented
I just realized I included rendering in the title of the issue. I meant recording, but I'll make a separate issue for that. Sorry for the confusion haha, playing should be fine for this PR.

2022-10-14 18:34 UTC, yvz5 commented
When I check the tests, movie's ready property is always true. I can't seem to figure out why the tests are red. would you mind checking this ?

2022-10-15 10:07 UTC, yvz5 commented
@clabe45 I tried it with the `requestAnimationFrame` method but it the tests were always red. I can't seem to understand why, so I moved to a simpler solution. I use a while loop to check if the movie is ready. It can be improved with exponential backoff and a timeout but I think it fulfills the task at hand.

2022-10-15 11:53 UTC, clabe45 commented
Ok, if this fixes the tests let's do this. Can you fix the linter errors?

2022-10-15 18:56 UTC, clabe45 approved these changes
Looks good, thanks!

2022-10-15 18:56 UTC, merged