Fix Border not Working with Text Layer
etro-js/etro pull request #239
Opened 2023-08-07 21:26 UTC by FlandiaYingman

Fixes https://github.com/etro-js/etro/issues/236

I haven't run the commit hooks (`test:unit`, `test:smoke`, etc.), since the syntax of setting scoped environment variable (`ENV=XXX command`) doesn't work on windows. See https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json/27090755#27090755 and its comments for more details. I suggest using https://www.npmjs.com/package/cross-env to deal with this problem.

2023-08-12 14:58 UTC, clabe45 commented
Hi, sorry for the late reply. Just started a new job.

Thanks for letting me know about the commit hooks. Could you please open an issue for that?

Reviewing the PR now...

2023-08-12 15:15 UTC, clabe45 requested changes
Two things:
- Make sure `val(this, 'border', this.currentTime)` is not null before drawing the outline (it [can be null](https://etrojs.dev/docs/reference/layers/visual#border)).
- The entire text is white in the example, but it should be blue with a white outline.

2023-08-12 15:16 UTC, clabe45 commented
The checks passed, but until the commit hook issue gets fixed, you can manually run them on your local machine:
```sh
npm test:unit
npm test:smoke
npm test:integration
```

2023-08-12 15:21 UTC, clabe45 commented
Looking at this further, I'd say we should add a separate property `textBorder`, since `border` specifies how the outline of the layer's bounds should be rendered. In another issue/PR, we should also deprecate `color` and rename it to `textColor`. Thoughts?

2023-08-12 17:42 UTC, FlandiaYingman commented
Actually, the "commit hooks problem" doesn't relate to commit hooks. I have created a issue about it #240.

2023-08-12 17:43 UTC, FlandiaYingman commented
> Two things:
> 
> * Make sure `val(this, 'border', this.currentTime)` is not null before drawing the outline (it [can be null](https://etrojs.dev/docs/reference/layers/visual#border)).
> * The entire text is white in the example, but it should be blue with a white outline.

I will try to fix those problems.

2023-08-12 18:02 UTC, FlandiaYingman commented
> Looking at this further, I'd say we should add a separate property `textBorder`, since `border` specifies how the outline of the layer's bounds should be rendered. In another issue/PR, we should also deprecate `color` and rename it to `textColor`. Thoughts?

If I understand you correctly, you meant: 

![image](https://github.com/etro-js/etro/assets/9929037/e446c79b-6e7f-4ff6-8756-3fe48fcb25bd)

Then adding a separate property would be a good idea, since it allows users to assign different styles on "border" and "textBorder". But I'd say the new property name should be `stroke`, since it is unified with CanvasRenderingContext2D's `strokeText()` method. Also, following the convention, we usually use the word "border" to refer to something that is a rectangle, and use the work "stroke" to refer to something whose shape is irregular. You may google "text border" and "text stroke" to check which one is more conventional.

2023-08-13 01:34 UTC, clabe45 commented
Makes sense, thanks for opening the issue.

Yeah, that is the distinction I was making. Good point, `stroke` would be a better name. Glad you pointed that out!

Please also be sure to type `stroke` as an object, with the same fields as `border`:
- `color` - dynamic color object
- `thickness` - dynamic number

See [this article](https://etrojs.dev/docs/reference/dynamic-properties) for more info on dynamic properties.

Let me know if anything is unclear or doesn't look quite right.

2023-08-13 01:38 UTC, clabe45 commented
Correction:

`stroke` should be a dynamic object:

```ts
Dynamic<{
  color: Color
  thickness?: number
}>
```

2023-08-13 17:52 UTC, clabe45 requested changes
This looks great!! Good idea on how to implement the position.

One thing though, can you make `position` an enum? `textDirection` should be an enum as well, but that can wait for another issue/PR.

2023-08-13 17:52 UTC, clabe45 commented on src/layer/text.ts
> +    position?: 'inside' | 'center' | 'outside'
Can you make this an enum

2023-08-13 18:12 UTC, FlandiaYingman commented on src/layer/text.ts
> +    position?: 'inside' | 'center' | 'outside'
Sure

2023-08-13 22:22 UTC, clabe45 commented
Looks great, merging. Thanks again!!

2023-08-13 22:22 UTC, merged