Update README.md
etro-js/etro pull request #273
Opened 2024-05-23 05:19 UTC by miki-reynolds

Hyperlinked LICENSE to enhance accessibility and conform with other hyperlinked resources within README, e.g. `contribution guide`

2024-06-08 03:20 UTC, clabe45 requested changes
Thanks! Small change needed

2024-06-08 03:20 UTC, clabe45 commented on README.md
> +Distributed under GNU General Public License v3. See [LICENSE](https://github.com/miki-reynolds/etro/blob/e0c25caa5af3ca61e20a0418816a682b2ecfcd3f/LICENSE) for more
Does `[LICENSE](LICENSE)` work?

2024-06-10 21:09 UTC, miki-reynolds commented on README.md
> +Distributed under GNU General Public License v3. See [LICENSE](https://github.com/miki-reynolds/etro/blob/e0c25caa5af3ca61e20a0418816a682b2ecfcd3f/LICENSE) for more
Yeah that works too :) Thanks!

2024-06-11 06:25 UTC, clabe45 approved these changes

2024-06-11 06:33 UTC, merged